### ISSUE TITLE
Beaker-rspec should support passing default options to beaker

### ISSUE THREAD

**Issue by nemski** [puppetlabs/beaker-rspec#57]
While I understand using environmental variables to pass options such as "provision" or "destroy" to beaker via beaker-rspec, this isn't efficient if I want to make "provision=no" and/or "destroy=no" a default when I run my tests.

Beaker-rpec should support setting these defaults via the acceptance spec helper which can be merged with the spec_helper.rb defaults and over-written by any environmental variables.

I'm not sure how to accomplish this, since the spec_helper.rb gets executed before my acceptance spec helper.

**Comment by anodelman** [comment]
I believe that this would be resolved with https://tickets.puppetlabs.com/browse/BKR-166.

If not, please file a new ticket here: https://tickets.puppetlabs.com/browse/BKR/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel
